2021-08-12 21:16:43,552 INFO Watching for file changes with StatReloader autoreload
2021-08-12 21:17:15,579 ERROR Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS. exception
2021-08-12 21:17:15,581 WARNING Bad Request: / log
2021-08-12 21:17:24,273 ERROR Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS. exception
2021-08-12 21:17:24,274 WARNING Bad Request: /posts/ log
2021-08-12 21:18:02,004 INFO /home/river/NewsBlog/NewsBlog/settings.py changed, reloading. autoreload
2021-08-12 21:18:02,402 INFO Watching for file changes with StatReloader autoreload
2021-08-12 21:22:26,205 INFO /home/river/NewsBlog/news/views.py changed, reloading. autoreload
2021-08-12 21:22:26,543 INFO Watching for file changes with StatReloader autoreload
2021-08-12 21:22:58,109 INFO /home/river/NewsBlog/news/views.py changed, reloading. autoreload
2021-08-12 21:22:58,422 INFO Watching for file changes with StatReloader autoreload
2021-08-12 21:26:41,429 INFO /home/river/NewsBlog/NewsBlog/settings.py changed, reloading. autoreload
2021-08-12 21:26:41,828 INFO Watching for file changes with StatReloader autoreload
2021-08-12 21:27:34,251 WARNING Not Found: / log
2021-08-12 21:27:35,102 INFO /home/river/NewsBlog/news/views.py changed, reloading. autoreload
2021-08-12 21:27:35,512 INFO Watching for file changes with StatReloader autoreload
2021-08-12 21:27:41,387 ERROR Internal Server Error: /posts/ log
Traceback (most recent call last):
  File "/home/river/NewsBlog/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/river/NewsBlog/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/river/NewsBlog/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/river/NewsBlog/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/river/NewsBlog/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/river/NewsBlog/venv/lib/python3.9/site-packages/django/views/generic/list.py", line 157, in get
    context = self.get_context_data()
  File "/home/river/NewsBlog/news/views.py", line 25, in get_context_data
    context = {**super().gt_context_data(*args, **kwargs),
AttributeError: 'super' object has no attribute 'gt_context_data'
2021-08-12 21:28:38,787 INFO /home/river/NewsBlog/news/views.py changed, reloading. autoreload
2021-08-12 21:28:39,240 INFO Watching for file changes with StatReloader autoreload
